name       : kscreen
version    : 5.13.4
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/kscreen-5.13.4.tar.xz : 43f78c55cca7c14aa1ae697fbda2f2179e73e65c8850d5e38ad164d538854b51
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
