name       : kscreen
version    : 5.17.2
release    : 40
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/kscreen-5.17.2.tar.xz : 0c7ad59ebf89cbf74a748aac6c7d08007b48170d1c18affbf2b230809e487957
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
