name       : kscreen
version    : 5.21.4
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.4/kscreen-5.21.4.tar.xz : d9d1225d5e4d5e062275c88bb879b96bde0167783d1a3722e737baa67dad3ed9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
optimize   : lto
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Sensors)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
