name       : kscreen
version    : 5.11.0
release    : 5
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kscreen-5.11.0.tar.xz : f1124d51195e9af80968d4a64a9e6297a3d572c2666cc753701b9e838a13d664
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
