name       : kscreen
version    : 5.11.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kscreen-5.11.1.tar.xz : 19bd0d5b17562c1ca9be952c76ad5fd451e289b581bdf17d9cbd338553796dea
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
