name       : kscreen
version    : 5.16.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/kscreen-5.16.3.tar.xz : 3c95f590ddc3483e2828585263feb2caa3e32c59f1b92f6aca23309565d4e139
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
