name       : kscreen
version    : 5.10.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.10.5/kscreen-5.10.5.tar.xz : 6e9f010165b1abc77c355c730cadecb88e55e1812d0d0db8d84a5acc89c20ba9
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
