name       : kscreen
version    : 5.23.2
release    : 72
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.2/kscreen-5.23.2.tar.xz : 9b100ba19b51a51f4c4084f7c17f175f3f21beec6c662c6f1d75ed127df380f1
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
optimize   : lto
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Sensors)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
