name       : kscreen
version    : 5.17.5
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/kscreen-5.17.5.tar.xz : de8a00b33d0254245a53a5c097347aa86709d415754b3e3c675eef8fb4fe5bc0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kiconthemes-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - plasma-framework-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
