name       : kscreen
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/kscreen-5.9.5.tar.xz : d1f1fe291763fbe14ccdffaf48c2540ecd4dc1b9fa88da1930c02ca36580c0b5
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
