name       : kscreen
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/kscreen-5.10.3.tar.xz : d49e0511540554322e1ae81130e1c320db7027455513da26e202e5e86b55880e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - qt5-graphicaleffects
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
